### ISSUE TITLE
KeyError: 'name' processing name-server leaf-list

### ISSUE THREAD

**Issue by kecorbin** [cmoberg/nso-ansible-demo#1]
**UPDATE** I've tried this with NSO 4.5.1 and 4.5.3, as well as trying the netsim path outlined in README and am still stuck with similar issues. 

Great project, I'm trying to replicate this demo using real devices already registered in NSO and am having some issues.  This could be something simple that I'm missing, but I found the docs a bit confusing.

I'm using `ansible 2.5.0b1`
After capturing the output from the curl command and converting to yaml, there is a step. 

**Paste the output into verify-device-tmpl.yaml under the line with the device name. Remember to indent correctly.**

It's unclear to me where that is such that an error is not generated. I read this to mean that `verify-device-tmpl.yaml` should look like this

```
          device:
            - name: "{{ device }}"
              top:
                tailf-ncs:config:
                  tailf-ned-cisco-ios:EXEC:
                    operations:
                      default: /api/config/devices/device/headend/config/ios:EXEC/_operations/default
                      exec: /api/config/devices/device/headend/config/ios:EXEC/_operations/exec
                  tailf-ned-cisco-ios:cached-show:
                    version:
                      license:
                        level: ax
                        type: Default. No valid license found.
                      model: CSR1000V
                      version: 16.5.1b
```

However this produces error:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "no child in /ncs:devices/device{headend} with name top. children ncs:name,ncs:address,ncs:port,ncs:remote-node,ncs:ssh,ncs:description,ncs:location,ncs:authgroup,ncs:device-type,ncs:device-profile,ncs:connect-timeout,ncs:read-timeout,ncs:write-timeout,ncs:ssh-keep-alive,ncs:trace,ncs:ned-settings,ncs:commit-queue,ncs:session-pool,ncs:no-overwrite,ncs:out-of-sync-commit-behaviour,choice-lsa,ncs:active-settings,ncs:live-status-protocol,ncs:state,ncs:source,ncs:capability,ncs:module,ncs:platform,ncs:config,ncs:live-status,ncs:rpc,ncs:netconf-notifications,ncs:service-list,ncs:snmp-notification-address,al:alarm-summary,ncs:copy-capabilities,ncs:find-capabilities,ncs:add-capability,ncs:apply-template,ncs:instantiate-from-other-device,ncs:compare-config,ncs:sync-from,ncs:sync-to,ncs:check-sync,ncs:check-yang-modules,ncs:connect,ncs:disconnect,ncs:ping,ncs:delete-config,ncs:scp-to,ncs:scp-from"}
```

Moving it to other indentation levels, generally produces key error on `top`
```
'dict object' has no attribute 'top'
```
TIA,
Kevin
